### ISSUE TITLE
Doesn’t work with user agent above Firefox/57.0

### ISSUE THREAD

**Issue by lukasfink1** [vladikoff/netflix-1080p-firefox#8] opened 2018-06-06 21:17 UTC
The plugin doesn’t work with newer user agents. To be more specific my user agent is `Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0`.
I tried different agents and the latest version that seems to work is 57 (`Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0`).
The same applies to Windows user agents: These also work only until version 57.

**Comment by fosspill** [comment] 2018-06-17 19:09
This.. This is really weird..
I was wondering why it stopped working, and this is indeed the solution.

What the fuck.

**Comment by saftle** [comment] 2018-06-17 21:48
I can confirm that the addon sadly no longer works. Also, if I enter the user agent in manually via about:config or via the user agent string switcher addon, Netflix instead no longer works.

It appears the chrome addon that the addon is based on works and has been updated recently.

**Comment by Termuellinator** [comment] 2018-07-06 18:47
Just discovered this addon - can confirm that it (at least mostly) works with user agent for version 57.
Don't know if the cases where i get only 480p are a fault of this addon or Netflix-BS ^^

**Comment by fosspill** [comment] 2018-07-07 08:55
lukas, that makes little sense in this issue. The problem is that user agent has to be set to firefox 57 for this plugin to work. I don't think that's related to HDCP.

**Comment by Termuellinator** [comment] 2018-07-07 09:13
i think lukas is adressing my 480p-issue...and for that his explanation makes perfect sense, so thank you :)

**Comment by informatorius** [comment] 2018-11-24 13:16
Fixed in latest version, can be closed

**Closed** 2018-11-24 21:44 UTC
